trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk'
    inputs:
      packageType: sdk
      version: '7.0.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: DotNetCoreCLI@2
    displayName: 'Install dotnet tools'
    inputs:
      command: 'custom'
      custom: 'tool'
      arguments: 'restore'

  - task: PowerShell@2
    displayName: 'GitVersion'
    inputs:
      targetType: 'inline'
      script: 'dotnet gitversion /l console /output buildserver /updateAssemblyInfo'

  - task: DotNetCoreCLI@2
    displayName: 'Publish Vinmonopolet.Web'
    inputs:
      command: publish
      publishWebProjects: false
      arguments: 'src/Vinmonopolet.Web/Vinmonopolet.Web.csproj -c Release -o "$(Build.ArtifactStagingDirectory)/webapp" /p:Version=$(GitVersion.MajorMinorPatch) --runtime linux-x64 --self-contained false'
      zipAfterPublish: false
      modifyOutputPath: false

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'